### ISSUE TITLE
How to check if session exists globally

### ISSUE THREAD

**Issue by peoray** [ioadres/vue-sessions#1]
In the documentation, to check if a session exists on a component, we need to do:

```
 beforeCreate: function () {
    if (!this.$session.exists()) {
      this.$router.push('/')
    }
```
This will check if a session exists, else redirect back to homepage.

I have many components, and doing this on each of them feels like WET code, so I decided to do it on the `router.js` file

```
import VueEasySession from 'vue-easysession'
var session = VueEasySession.getInstance()
if(!session.exists()) {
   next('/')
     } else {
      next();
    }
}
```

It isn't working and I'm getting an error:
`[vue-router] uncaught error during route navigation:`
`Invalid Object` with a dropdown of many files

**Comment by ioadres** [comment]
you can use the expireSession for redirect to Login page.

**this.$session.start(exp : milliseconds),** the parameter exp is optional and indicate the time of expiration the session(millisecond)

```
var options = {
    persist: true,
    keySession: 'myKeySession',
    expireSessionCallback: function () {
        window.location.href = '/'
    }
}
```

**expireSessionCallback: function () {
        window.location.href = '/'
    }**

If this does not work, I will try to find a solution for you problem because as you said : "doing this on each component feels like WET" is true!

**Comment by peoray** [comment]
Thanks, just seeing this now, I'll try the code above and tell you how it went

**Comment by peoray** [comment]
Tried this and got confused too. Not sure you understand the issue or maybe I didn't explain well. I'll like to further discuss this to have a solution. 

Basically, all I'm saying is how to be able to use the code that checks if a session exists for each component and put it inside router.js so it can be used with a beforeRoute method so we don't have to keep writing the same code for every component.
I hope this is clear this time around? :slightly_smiling_face:  Also, if there is any way I can contribute, I'm not good at it but willing to learn
